version: 2.1

commands:
  install_dependencies:
    parameters:
      package_manager:
        type: string
    steps:
      - run: << parameters.package_manager >> clean all && << parameters.package_manager >> update && << parameters.package_manager >> install curl bash coreutils -y
  configure_and_execute:
    steps:
      - run:
          name: Configure environment and execute WireGuard Manager
          command: |
            curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
            chmod +x /usr/local/bin/wireguard-manager.sh
            bash /usr/local/bin/wireguard-manager.sh --install

jobs:
  ubuntu_test:
    parameters:
      image:
        type: string
      package_manager:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - install_dependencies:
          package_manager: << parameters.package_manager >>
      - configure_and_execute

  debian_test:
    parameters:
      image:
        type: string
      package_manager:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - install_dependencies:
          package_manager: << parameters.package_manager >>
      - configure_and_execute

  centos_test:
    parameters:
      image:
        type: string
      package_manager:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - install_dependencies:
          package_manager: << parameters.package_manager >>
      - configure_and_execute

  alpine_test:
    parameters:
      image:
        type: string
      package_manager:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apk update && apk add --no-cache curl bash coreutils
      - configure_and_execute

workflows:
  version: 2
  comprehensive_tests:
    jobs:
      - ubuntu_test:
          image: ubuntu:latest
          package_manager: apt-get
      - debian_test:
          image: debian:latest
          package_manager: apt-get
      - centos_test:
          image: centos:latest
          package_manager: yum
      - alpine_test:
          image: alpine:latest
          package_manager: apk
