version: 2.1

jobs:
  ubuntu_based_test:
    docker:
      # Use a Docker image where you might need to install git manually.
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
          name: Update and install git, ssh (if needed), and other dependencies
          command: |
            apt-get update && apt-get install -y curl bash resolvconf git
            # Install ssh only if you need it for operations like accessing private repositories
            # apt-get install -y ssh
      - run:
          name: Download and prepare WireGuard Manager script
          command: |
            curl https://raw.githubusercontent.com/complexorganizations/wireguard-manager/main/wireguard-manager.sh --create-dirs -o /usr/local/bin/wireguard-manager.sh
            chmod +x /usr/local/bin/wireguard-manager.sh
      - run:
          name: Execute script
          command: bash /usr/local/bin/wireguard-manager.sh --install

workflows:
  version: 2
  comprehensive_tests:
    jobs:
      - ubuntu_based_test
